apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjek5UTXlPRGcxTnl3aWFXRjBJam94TnpNMU16STRPRFUzZlEuYW9JYkhDVFUwNFR4UHV5eC1iM0JOYUlOZElYdlVWaFo3UGpPQ2JvV2puOA==
